version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd clerical-core && npm install
            - run: cd clerical-core && npm test
  publish:
    branches:
      only:
        - master
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: cd clerical-core && npm publish
workflows:
    build-and-test:
      jobs:
        - build-and-test
